name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1 # Specify the PHP version
          extensions: mbstring, pdo, mysqli
          coverage: none

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      # Step 4: Verify the FPDF installation
      - name: Verify FPDF is installed
        run: |
          if [ ! -f "vendor/autoload.php" ]; then
            echo "FPDF or dependencies are missing!";
            exit 1;
          fi

      # Step 5: Run Tests
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit

      # Step 6: Validate the export feature
      - name: Test FPDF Export
        run: |
          php export_test_script.php
        env:
          PDF_OUTPUT_PATH: "tests/export_output.pdf"
